### ISSUE TITLE
D cache is not enabled

### ISSUE THREAD

**Issue by xuzihan351** [rustsbi/rustsbi-hpm#4]
The memory access is slow because dcache is not enabled. See Andes D45 CSRs : CSR_MCACHE_CTL (0x7CA) bit1 and bit9

**Comment by tfx2001** [comment]
During testing I found that the Linux kernel runs with access fault when d-cache is enabled, so it is not enabled at this time. You can try enabling it and see what happens. PR is welcome if you can fix it.

**Comment by xuzihan351** [comment]
I only choose IMC ISA, and run **ramspeed** for a while. Is there any additional information that can lead to the access fault?

**Comment by tfx2001** [comment]
https://github.com/hpm-rs/hpm-rt/blob/66ffb7d7a65d7251d0b47db9599d36cefc4d6703/src/cache.rs#L150-L157
